require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
  - 'lib/thredded_create_app/tasks/*/*.rb'

Metrics/ClassLength:
  Max: 125

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 25

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
  - 'lib/thredded_create_app/tasks/setup_app_skeleton/application_helper_methods.rb'

Style/SignalException:
  EnforcedStyle: semantic

Style/StderrPuts:
  Enabled: false
